import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const handleEmail = async (event) => {
  event.preventDefault();
  const res = await fetch("/api/send-email", {
    method: "GET",
  });
    if (res.ok) {
      console.log("Email sent generated successfully");
    } else {
      console.log("Email not sent");
    }
  }

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <form onSubmit={handleEmail}>
      <button type="submit">Send Email</button>
      </form>
      
        
      </main>
    </>
  )
}
